import type { Project } from './types'

// AUTO-GENERATED by scripts/build-projects.ts — do not edit by hand.
// Every public repo with a detailed README (empty / stub repos filtered out).
export const generatedProjects: Project[] = [
  {
    "slug": "scm-using-mcp-and-llm",
    "title": "SCM Using MCP And LLM",
    "repo": "SCM-using-MCP-and-LLM",
    "domain": "Agentic",
    "blurb": "A pet-retail supply-chain platform where an AI agent reasons over a live data warehouse and tells you what to do — not just what happened.",
    "tech": [
      "Python",
      "JavaScript",
      "PyTorch",
      "CatBoost",
      "Transformers",
      "RAG",
      "MCP",
      "OpenAI",
      "Anthropic"
    ],
    "url": "https://github.com/shiva-shivanibokka/SCM-using-MCP-and-LLM"
  },
  {
    "slug": "churn-intelligence-platform",
    "title": "Churn Intelligence Platform",
    "repo": "Churn-Intelligence-Platform",
    "domain": "Classical ML",
    "blurb": "End-to-end decision intelligence platform: behavioral segmentation → per-cohort churn prediction → uplift modeling → 12-tool AI retention agent → closed-loop outcome tracking.",
    "tech": [
      "Python",
      "TypeScript",
      "PLpgSQL",
      "scikit-learn",
      "XGBoost",
      "CatBoost",
      "FastAPI",
      "Streamlit",
      "Docker"
    ],
    "url": "https://github.com/shiva-shivanibokka/Churn-Intelligence-Platform"
  },
  {
    "slug": "codepilot-agent",
    "title": "CodePilot Agent",
    "repo": "CodePilot-Agent",
    "domain": "Agentic",
    "blurb": "An autonomous coding agent that takes a natural language task, plans an implementation, writes code across multiple files, runs it in an isolated sandbox, debugs failures, and delivers working results — all streamed to you in real time.",
    "tech": [
      "Python",
      "LangGraph",
      "Anthropic",
      "FastAPI",
      "Gradio",
      "Docker",
      "Pydantic"
    ],
    "url": "https://github.com/shiva-shivanibokka/CodePilot-Agent"
  },
  {
    "slug": "data-analytics-portfolio",
    "title": "Data Analytics Portfolio",
    "repo": "Data-Analytics-Portfolio",
    "domain": "Data Science",
    "blurb": "A complete data analytics case study built around FlowDesk — a fictional B2B SaaS project management company (think Asana / Monday.com). Seven notebooks cover every analytical skill tested in DA and DS interviews at Meta, Airbnb, LinkedI…",
    "tech": [
      "Jupyter Notebook",
      "Python",
      "NumPy",
      "pandas"
    ],
    "url": "https://github.com/shiva-shivanibokka/Data-Analytics-Portfolio"
  },
  {
    "slug": "resumeforge",
    "title": "ResumeForge",
    "repo": "ResumeForge",
    "domain": "LLMs & GenAI",
    "blurb": "Forge a résumé the job can't ignore — AI résumé tailoring with a true one-page guarantee.",
    "tech": [
      "Python",
      "TypeScript",
      "Transformers",
      "RAG",
      "OpenAI",
      "Anthropic",
      "FastAPI",
      "Docker",
      "React"
    ],
    "url": "https://github.com/shiva-shivanibokka/ResumeForge"
  },
  {
    "slug": "fraud-detection-system",
    "title": "Fraud Detection System",
    "repo": "Fraud-Detection-System",
    "domain": "MLOps",
    "blurb": "An end-to-end, deployed fraud-detection platform on free-tier infra — model registry → CI → deploy — pairing a real-time tabular scoring API with a graph-neural-network benchmark on real Bitcoin fraud data.",
    "tech": [
      "Python",
      "JavaScript",
      "PyTorch",
      "scikit-learn",
      "XGBoost",
      "CatBoost",
      "LightGBM",
      "Transformers",
      "RAG"
    ],
    "url": "https://github.com/shiva-shivanibokka/Fraud-Detection-System"
  },
  {
    "slug": "rag-vs-cag-showdown",
    "title": "RAG Vs CAG Showdown",
    "repo": "RAG-vs-CAG-Showdown",
    "domain": "LLMs & GenAI",
    "blurb": "A modular benchmarking framework that compares Context Augmented Generation and Retrieval Augmented Generation head-to-head. Measures latency, token cost, and answer quality via LLM-as-judge scoring across factual, multi-hop, and reasoning tasks using the Anthropic Claude API",
    "tech": [
      "Python",
      "JavaScript",
      "RAG",
      "FAISS",
      "OpenAI",
      "Anthropic",
      "FastAPI",
      "Docker",
      "React"
    ],
    "url": "https://github.com/shiva-shivanibokka/RAG-vs-CAG-Showdown"
  },
  {
    "slug": "take-home-project",
    "title": "Take Home Project",
    "repo": "take-home-project",
    "domain": "LLMs & GenAI",
    "blurb": "Confer Inc. · AI/ML Engineering Take-Home · Assignment 5 of 5",
    "tech": [
      "TypeScript",
      "JavaScript",
      "PLpgSQL",
      "OpenAI",
      "Anthropic",
      "Ollama",
      "AWS",
      "React",
      "Next.js"
    ],
    "url": "https://github.com/shiva-shivanibokka/take-home-project"
  },
  {
    "slug": "search-ranking-system",
    "title": "Search Ranking System",
    "repo": "Search-Ranking-System",
    "domain": "Classical ML",
    "blurb": "A full production-grade search and ranking system, built the way a senior ML engineer would build it at a company like YouTube, Spotify, or Google. It takes a user's search query, understands what they mean, finds the most relevant passa…",
    "tech": [
      "Python",
      "PyTorch",
      "XGBoost",
      "Transformers",
      "FAISS",
      "Anthropic",
      "FastAPI",
      "Gradio",
      "Docker"
    ],
    "url": "https://github.com/shiva-shivanibokka/Search-Ranking-System"
  },
  {
    "slug": "hireview",
    "title": "HireView",
    "repo": "HireView",
    "domain": "Full-Stack / Product",
    "blurb": "HireView is a job search aggregator that searches hundreds of company career pages simultaneously so you never have to visit each one manually. You type a job title or company name, and HireView scrapes the ATS platforms those companies…",
    "tech": [
      "TypeScript",
      "Python",
      "JavaScript",
      "Transformers",
      "Anthropic",
      "FastAPI",
      "React",
      "Next.js",
      "Tailwind"
    ],
    "url": "https://github.com/shiva-shivanibokka/HireView"
  },
  {
    "slug": "gradient-descent-and-optimizers",
    "title": "Gradient Descent And Optimizers",
    "repo": "Gradient-Descent-and-Optimizers",
    "domain": "Deep Learning",
    "blurb": "A production-grade optimizer benchmarking library and interactive demo. Every major gradient descent variant, adaptive optimizer, and LR scheduler — implemented from scratch in NumPy, tested with pytest, tracked with MLflow, and deployed…",
    "tech": [
      "Python",
      "Jupyter Notebook",
      "PyTorch",
      "Transformers",
      "Gradio",
      "Docker",
      "MLflow",
      "NumPy",
      "Pydantic"
    ],
    "url": "https://github.com/shiva-shivanibokka/Gradient-Descent-and-Optimizers"
  },
  {
    "slug": "sql-and-database-skills",
    "title": "SQL And Database Skills",
    "repo": "SQL-and-Database-Skills",
    "domain": "Data Science",
    "blurb": "Production-grade SQL from fundamentals through FAANG-level interview patterns — demonstrated on a realistic 2.6M-row synthetic e-commerce database.",
    "tech": [
      "Jupyter Notebook",
      "Python",
      "pandas"
    ],
    "url": "https://github.com/shiva-shivanibokka/SQL-and-Database-Skills"
  },
  {
    "slug": "competitor-insight-engine",
    "title": "Competitor Insight Engine",
    "repo": "Competitor-Insight-Engine",
    "domain": "LLMs & GenAI",
    "blurb": "AI-powered tool that scrapes any company's website, finds real-time competitors via Tavily search, and generates a full competitive intelligence report — including market comparison and strategic recommendations — using any LLM of your choice.",
    "tech": [
      "Jupyter Notebook",
      "Python",
      "OpenAI",
      "Anthropic",
      "Ollama"
    ],
    "url": "https://github.com/shiva-shivanibokka/Competitor-Insight-Engine"
  },
  {
    "slug": "multi-horizon-stock-forecasting-ai-model",
    "title": "Multi Horizon Stock Forecasting AI Model",
    "repo": "Multi-Horizon-Stock-Forecasting-AI-Model",
    "domain": "Deep Learning",
    "blurb": "Multi-Horizon Stock Price Forecasting using Transformer, LSTM, RNN, and Random Forest on S&P 500 data.",
    "tech": [
      "Python",
      "JavaScript",
      "PyTorch",
      "scikit-learn",
      "Flask",
      "Docker",
      "MLflow",
      "Next.js",
      "NumPy"
    ],
    "url": "https://github.com/shiva-shivanibokka/Multi-Horizon-Stock-Forecasting-AI-Model"
  },
  {
    "slug": "supply-chain-demand-agent",
    "title": "Supply Chain Demand Agent",
    "repo": "Supply-Chain-Demand-Agent",
    "domain": "LLMs & GenAI",
    "blurb": "Agentic RAG pipeline for supply chain demand forecasting using LLMs, time-series models, and MLOps",
    "tech": [
      "Python",
      "Jupyter Notebook",
      "PyTorch",
      "Transformers",
      "RAG",
      "ChromaDB",
      "OpenAI",
      "Anthropic",
      "Streamlit"
    ],
    "url": "https://github.com/shiva-shivanibokka/Supply-Chain-Demand-Agent"
  },
  {
    "slug": "llm-halucination-detection",
    "title": "LLM Halucination Detection",
    "repo": "LLM-Halucination-Detection",
    "domain": "NLP",
    "blurb": "NLI-based hallucination detection pipeline. Flags unsupported LLM claims using DeBERTa-v3, assigns a hallucination confidence score per sentence, and grounds responses against source documents via ChromaDB.",
    "tech": [
      "Python",
      "Transformers",
      "ChromaDB",
      "OpenAI",
      "Anthropic",
      "Ollama",
      "FastAPI",
      "Gradio",
      "Playwright"
    ],
    "url": "https://github.com/shiva-shivanibokka/LLM-Halucination-Detection"
  },
  {
    "slug": "ml-system-design-retraining-pipeline",
    "title": "ML System Design Retraining Pipeline",
    "repo": "ML-System-Design-Retraining-Pipeline",
    "domain": "ML System Design",
    "blurb": "A production-grade automated model lifecycle system for a credit risk LightGBM model — built to reflect how Uber, Airbnb, Netflix, and Google actually manage model decay in production.",
    "tech": [
      "Python",
      "XGBoost",
      "LightGBM",
      "Streamlit",
      "Docker",
      "MLflow"
    ],
    "url": "https://github.com/shiva-shivanibokka/ML-System-Design-Retraining-Pipeline"
  },
  {
    "slug": "ml-system-design-model-serving",
    "title": "ML System Design Model Serving",
    "repo": "ML-System-Design-Model-Serving",
    "domain": "ML System Design",
    "blurb": "A production-grade model deployment system built around the question every ML engineering interview asks:",
    "tech": [
      "Python",
      "PyTorch",
      "Transformers",
      "FastAPI",
      "Gradio",
      "Docker",
      "Postgres"
    ],
    "url": "https://github.com/shiva-shivanibokka/ML-System-Design-Model-Serving"
  },
  {
    "slug": "ml-system-design-feature-store",
    "title": "ML System Design Feature Store",
    "repo": "ML-System-Design-Feature-Store",
    "domain": "ML System Design",
    "blurb": "A production-grade feature store built to the same architectural standards as Uber Michelangelo , DoorDash , and Twitter Cortex — the systems that serve billions of ML predictions per day.",
    "tech": [
      "Python",
      "LightGBM",
      "FastAPI",
      "Gradio",
      "Docker",
      "MLflow",
      "Postgres",
      "Plotly"
    ],
    "url": "https://github.com/shiva-shivanibokka/ML-System-Design-Feature-Store"
  },
  {
    "slug": "ml-system-design-batch-inference",
    "title": "ML System Design Batch Inference",
    "repo": "ML-System-Design-Batch-Inference",
    "domain": "ML System Design",
    "blurb": "Production-grade nightly batch scoring system that scores 1,000,000 customers for churn probability using PySpark distributed inference, orchestrated by Apache Airflow, served via FastAPI, and monitored through a Gradio dashboard.",
    "tech": [
      "Python",
      "LightGBM",
      "FastAPI",
      "Gradio",
      "Docker",
      "Postgres",
      "pandas",
      "Plotly",
      "Pydantic"
    ],
    "url": "https://github.com/shiva-shivanibokka/ML-System-Design-Batch-Inference"
  },
  {
    "slug": "ml-model-efficiency-toolkit",
    "title": "ML Model Efficiency Toolkit",
    "repo": "ML-Model-Efficiency-Toolkit",
    "domain": "Deep Learning",
    "blurb": "A comprehensive, modular framework for compressing and benchmarking deep learning models using three industry-standard techniques — Quantization , Pruning , and Knowledge Distillation — applied to both vision (ResNet-50, CIFAR-10) and NL…",
    "tech": [
      "Python",
      "Jupyter Notebook",
      "PyTorch",
      "Transformers",
      "AWS",
      "NumPy",
      "pandas"
    ],
    "url": "https://github.com/shiva-shivanibokka/ML-Model-Efficiency-Toolkit"
  },
  {
    "slug": "tisch-ml-model",
    "title": "Tisch ML Model",
    "repo": "Tisch-ML-Model",
    "domain": "Classical ML",
    "blurb": "A machine learning classification project using the TISCH (Tumor Immune Single-cell Hub) dataset, applying machine learning techniques to classify cell types across cancer samples from single-cell RNA sequencing data.",
    "tech": [
      "Jupyter Notebook",
      "scikit-learn",
      "XGBoost",
      "NumPy",
      "pandas"
    ],
    "url": "https://github.com/shiva-shivanibokka/Tisch-ML-Model"
  },
  {
    "slug": "sepsis-ml-model",
    "title": "Sepsis ML Model",
    "repo": "Sepsis-ML-Model",
    "domain": "Classical ML",
    "blurb": "Early prediction of sepsis in ICU patients using Random Forest and XGBoost on the PhysioNet/CinC Challenge 2019 dataset. Covers the full ML pipeline: EDA, preprocessing, feature selection, and model tuning. Built as an introductory project for students learning applied machine learning.",
    "tech": [
      "Jupyter Notebook",
      "scikit-learn",
      "XGBoost",
      "NumPy",
      "pandas"
    ],
    "url": "https://github.com/shiva-shivanibokka/Sepsis-ML-Model"
  },
  {
    "slug": "cumida-ml-model",
    "title": "Cumida ML Model",
    "repo": "Cumida-ML-Model",
    "domain": "Classical ML",
    "blurb": "ML classification project using the CuMiDa Liver Cancer dataset, applying supervised learning techniques to classify liver cancer subtypes from curated microarray gene expression data.",
    "tech": [
      "Jupyter Notebook",
      "scikit-learn",
      "XGBoost",
      "NumPy",
      "pandas"
    ],
    "url": "https://github.com/shiva-shivanibokka/Cumida-ML-Model"
  },
  {
    "slug": "all-about-cross-validation",
    "title": "All About Cross Validation",
    "repo": "All-About-Cross-Validation",
    "domain": "Classical ML",
    "blurb": "Learn everything there is to learn about Cross Validation in ML.",
    "tech": [
      "Jupyter Notebook",
      "scikit-learn",
      "NumPy",
      "pandas"
    ],
    "url": "https://github.com/shiva-shivanibokka/All-About-Cross-Validation"
  },
  {
    "slug": "dive-deeper-into-linear-models",
    "title": "Dive Deeper Into Linear Models",
    "repo": "Dive-deeper-into-linear-models",
    "domain": "Classical ML",
    "blurb": "Let's move on from basic linear and logistic regression to some advanced techniques.",
    "tech": [
      "Jupyter Notebook",
      "scikit-learn",
      "XGBoost",
      "NumPy",
      "pandas"
    ],
    "url": "https://github.com/shiva-shivanibokka/Dive-deeper-into-linear-models"
  },
  {
    "slug": "basics-of-linear-and-logistic-regression",
    "title": "Basics Of Linear And Logistic Regression",
    "repo": "Basics-of-Linear-and-Logistic-Regression",
    "domain": "Classical ML",
    "blurb": "Learn everything about basics of Linear and Logistic regression end to end",
    "tech": [
      "Jupyter Notebook",
      "scikit-learn",
      "Transformers",
      "NumPy",
      "pandas"
    ],
    "url": "https://github.com/shiva-shivanibokka/Basics-of-Linear-and-Logistic-Regression"
  },
  {
    "slug": "data-preprocessing",
    "title": "Data Preprocessing",
    "repo": "Data-Preprocessing",
    "domain": "Classical ML",
    "blurb": "Learn all about data preprocessing for ML models",
    "tech": [
      "Jupyter Notebook",
      "scikit-learn",
      "XGBoost",
      "NumPy",
      "pandas"
    ],
    "url": "https://github.com/shiva-shivanibokka/Data-Preprocessing"
  },
  {
    "slug": "autograder-agent",
    "title": "AutoGrader Agent",
    "repo": "AutoGrader-Agent",
    "domain": "LLMs & GenAI",
    "blurb": "AI agent that auto-grades any Jupyter notebook (ML, RAG, NLP, CV, data analysis, algorithms). Upload a notebook, optionally provide your own rubric, set grading strictness, and get a structured report with scores per criterion, written feedback, strengths, and improvement suggestions. Built with LangGraph, nbformat, Pydantic, FastAPI, and Gradio.",
    "tech": [
      "Python",
      "Transformers",
      "LangGraph",
      "RAG",
      "OpenAI",
      "Anthropic",
      "FastAPI",
      "Gradio",
      "Pydantic"
    ],
    "url": "https://github.com/shiva-shivanibokka/AutoGrader-Agent"
  },
  {
    "slug": "llm-research-scraper",
    "title": "LLM Research Scraper",
    "repo": "LLM-research-scraper",
    "domain": "LLMs & GenAI",
    "blurb": "Simple to complex projects implemented using LLMs",
    "tech": [
      "Jupyter Notebook",
      "Anthropic"
    ],
    "url": "https://github.com/shiva-shivanibokka/LLM-research-scraper"
  },
  {
    "slug": "open-source-llms-api-wrapper",
    "title": "Open Source LLMs Api Wrapper",
    "repo": "open-source-LLMs-api-wrapper",
    "domain": "LLMs & GenAI",
    "blurb": "Using an API wrapper where the user selects an open source LLM model without changing any code.",
    "tech": [
      "Jupyter Notebook",
      "Python",
      "OpenAI",
      "Ollama"
    ],
    "url": "https://github.com/shiva-shivanibokka/open-source-LLMs-api-wrapper"
  },
  {
    "slug": "super-resolution-using-han",
    "title": "Super Resolution Using HAN",
    "repo": "Super_Resolution_using_HAN",
    "domain": "Deep Learning",
    "blurb": "Super Resolution using HAN (Holistic Attention Network) architecture",
    "tech": [
      "Python",
      "Jupyter Notebook",
      "PyTorch"
    ],
    "url": "https://github.com/shiva-shivanibokka/Super_Resolution_using_HAN"
  },
  {
    "slug": "wellnest-curated-health-web-app",
    "title": "Wellnest Curated Health Web App",
    "repo": "Wellnest-Curated-Health-Web-App",
    "domain": "Data Science",
    "blurb": "Wellnest is a lightweight wellness companion that helps users build sustainable habits through daily tracking, friendly competition, and smart recommendations. Users complete a short intake survey, sign up, and start logging habits like…",
    "tech": [
      "JavaScript",
      "Python",
      "Django",
      "Docker",
      "AWS"
    ],
    "url": "https://github.com/shiva-shivanibokka/Wellnest-Curated-Health-Web-App"
  }
]
